In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("C:\kaggle Dataset\Dataset .csv")

In [3]:
df.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [4]:
# dropping some colums which are not important
df.drop('Restaurant ID', axis=1, inplace=True) 
df.drop('Country Code', axis=1, inplace=True) 
df.drop('City', axis=1, inplace=True) 
df.drop('Address', axis=1, inplace=True) 
df.drop('Locality', axis=1, inplace=True) 
df.drop('Locality Verbose', axis=1, inplace=True) 
df.drop('Longitude', axis=1, inplace=True) 
df.drop('Latitude', axis=1, inplace=True) 
df.drop('Currency', axis=1, inplace=True) 
df.drop('Has Table booking', axis=1, inplace=True) 
df.drop('Has Online delivery', axis=1, inplace=True) 
df.drop('Is delivering now', axis=1, inplace=True) 
df.drop('Switch to order menu', axis=1, inplace=True) 
df.drop('Price range', axis=1, inplace=True) 
df.drop('Aggregate rating', axis=1, inplace=True) 
df.drop('Rating color', axis=1, inplace=True) 
df.drop('Rating text', axis=1, inplace=True) 
df.drop('Votes', axis=1, inplace=True)

In [5]:
df

Restaurant Name                          Cuisines  \
0             Le Petit Souffle        French, Japanese, Desserts   
1             Izakaya Kikufuji                          Japanese   
2       Heat - Edsa Shangri-La  Seafood, Asian, Filipino, Indian   
3                         Ooma                   Japanese, Sushi   
4                  Sambo Kojin                  Japanese, Korean   
...                        ...                               ...   
9546               Naml۱ Gurme                           Turkish   
9547              Ceviz A��ac۱   World Cuisine, Patisserie, Cafe   
9548                     Huqqa            Italian, World Cuisine   
9549               A���k Kahve                   Restaurant Cafe   
9550  Walter's Coffee Roastery                              Cafe   

      Average Cost for two  
0                     1100  
1                     1200  
2                     4000  
3                     1500  
4                     1500  
...                    ...  
9546                    80  
9547                   105  
9548                   170  
9549                   120  
9550                    55  

[9551 rows x 3 columns]

In [6]:
df.isnull().sum()

Restaurant Name         0
Cuisines                9
Average Cost for two    0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.isnull().sum()

Restaurant Name         0
Cuisines                0
Average Cost for two    0
dtype: int64

In [9]:
df.shape

(9542, 3)

In [10]:
# Checking missing vaalues for each col
missing_values = df.isna().sum() 
missing_values_column = df['Restaurant Name'].isna().sum() 
missing_values_column = df['Cuisines'].isna().sum() 
missing_values_column = df['Average Cost for two'].isna().sum()

In [11]:
df_clean = df.dropna() 
df_clean = df.dropna(subset=['Restaurant Name']) 
df_clean = df.dropna(subset=['Cuisines']) 
df_clean = df.dropna(subset=['Average Cost for two'])

In [12]:
df.describe(include="all")

Restaurant Name      Cuisines  Average Cost for two
count              9542          9542           9542.000000
unique             7437          1825                   NaN
top     Cafe Coffee Day  North Indian                   NaN
freq                 83           936                   NaN
mean                NaN           NaN           1200.326137
std                 NaN           NaN          16128.743876
min                 NaN           NaN              0.000000
25%                 NaN           NaN            250.000000
50%                 NaN           NaN            400.000000
75%                 NaN           NaN            700.000000
max                 NaN           NaN         800000.000000

In [13]:
from sklearn.preprocessing import LabelEncoder 

label_encoder = LabelEncoder() 
df['Restaurant Name'] = label_encoder.fit_transform(df['Restaurant Name']) 
df['Cuisines'] = label_encoder.fit_transform(df['Cuisines'])

In [14]:
df

Restaurant Name  Cuisines  Average Cost for two
0                3742       920                  1100
1                3167      1111                  1200
2                2892      1671                  4000
3                4700      1126                  1500
4                5515      1122                  1500
...               ...       ...                   ...
9546             4436      1813                    80
9547             1310      1824                   105
9548             3063      1110                   170
9549              512      1657                   120
9550             7231       331                    55

[9542 rows x 3 columns]

In [15]:
# USING RANDOM FOREST ALGO

X = df[['Restaurant Name', 'Average Cost for two']] 
Y = df['Cuisines']

In [16]:
from sklearn.preprocessing import StandardScaler

sc= StandardScaler()

sc.fit(X)
X= sc.transform(X)

In [17]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=5)  

In [18]:
from sklearn.tree import DecisionTreeClassifier

DEC_TREE = DecisionTreeClassifier(random_state=10,
                                   criterion="gini")


DEC_TREE.fit(X_train,Y_train)     
Y_pred = DEC_TREE.predict(X_test) 

print(list(zip(Y_test,Y_pred)))

[(1605, 1749), (1749, 1321), (828, 497), (1651, 1651), (1306, 1520), (331, 331), (1329, 1514), (794, 186), (497, 1244), (114, 258), (1306, 1306), (1306, 1306), (549, 497), (828, 828), (331, 331), (487, 487), (177, 1306), (254, 254), (1626, 1626), (331, 331), (1306, 1749), (1688, 575), (331, 331), (1126, 1124), (1520, 518), (1306, 1275), (1275, 1065), (828, 54), (1329, 1329), (385, 307), (1738, 281), (1031, 549), (1699, 1306), (255, 255), (828, 828), (791, 1320), (1559, 1715), (952, 1373), (1306, 549), (863, 1650), (1520, 1112), (828, 775), (1329, 1682), (1126, 497), (830, 1618), (177, 1306), (816, 331), (1329, 1329), (1737, 1773), (1275, 331), (312, 311), (1780, 497), (186, 230), (1262, 1020), (1306, 1275), (1136, 1749), (1288, 1288), (243, 1275), (331, 331), (1570, 1570), (257, 1105), (1323, 1323), (503, 1306), (1329, 841), (177, 1185), (537, 925), (54, 54), (1348, 497), (201, 828), (1667, 686), (1749, 1306), (549, 760), (1421, 1334), (40, 1783), (1207, 1161), (497, 201), (177, 774), 

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           6       0.11      0.14      0.12         7
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         1
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          16       1.00      1.00      1.00         1
          18       0.00      0.00      0.00         0
          20       0.00      0.00      0.00         0
          21       0.00      0.00      0.00  

C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\metrics\_cla

In [20]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(multi_class="multinomial")

classifier.fit(X_train,Y_train)      

Y_pred = classifier.predict(X_test)
print(Y_pred)

[1306 1306 1306 ... 1306 1306 1306]


In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         7
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         5
          35       0.00      0.00      0.00         1
          39       0.00      0.00      0.00  

In [ ]:
#  comparing Random Forest and Logistic Regression ,  Random Forest is Performing Better as compared to Logistic Regression.
Logistic Regression - Accuracy of the model:  0.09360810338805449
Random Forest -Accuracy of the model:  0.21830247991617185